spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/template?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: 192.168.1.200
    password: 999888V
    timeout: 2000
    database: 5
    civ:
      database: 6
    disaster_civ:
      database: 8
    port: 6379

whitelist: "11111"

logging:
  level:
    com.fineway.disaster.usregion.serv: DEBUG